-- KPCA Portal Database Schema
-- Run this in the Supabase SQL Editor

-- 1. Profiles Table (Extends Auth.Users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    email TEXT,
    role TEXT DEFAULT 'MANAGER', -- PARTNER, DIRECTOR, MANAGER
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Clients Table
CREATE TABLE IF NOT EXISTS public.clients (
    client_code TEXT PRIMARY KEY,
    client_name TEXT NOT NULL,
    group_name TEXT,
    industry TEXT,
    relationship_partner UUID REFERENCES public.profiles(id),
    primary_contact_name TEXT,
    primary_contact_email TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES public.profiles(id)
);

-- 3. Proposals Table
CREATE TABLE IF NOT EXISTS public.proposals (
    proposal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_code TEXT REFERENCES public.clients(client_code) ON DELETE CASCADE,
    service_line TEXT,
    scope_summary TEXT,
    estimated_fees DECIMAL DEFAULT 0,
    issued_date DATE,
    status TEXT DEFAULT 'Draft',
    outcome_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES public.profiles(id)
);

-- 4. Assignments Table
CREATE TABLE IF NOT EXISTS public.assignments (
    assignment_code TEXT PRIMARY KEY,
    client_code TEXT REFERENCES public.clients(client_code) ON DELETE CASCADE,
    proposal_id BIGINT REFERENCES public.proposals(proposal_id),
    title TEXT NOT NULL,
    service_line TEXT,
    start_date DATE,
    end_date DATE,
    partner_lead UUID REFERENCES public.profiles(id),
    director UUID REFERENCES public.profiles(id),
    manager UUID REFERENCES public.profiles(id),
    contracted_fee DECIMAL DEFAULT 0,
    status TEXT DEFAULT 'Planned',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES public.profiles(id)
);

-- 5. Invoices Table
CREATE TABLE IF NOT EXISTS public.invoices (
    invoice_no TEXT PRIMARY KEY,
    assignment_code TEXT REFERENCES public.assignments(assignment_code) ON DELETE CASCADE,
    invoice_date DATE NOT NULL,
    amount_before_tax DECIMAL DEFAULT 0,
    gst_pct DECIMAL DEFAULT 18.00,
    due_date DATE,
    status TEXT DEFAULT 'Issued',
    amount_with_tax DECIMAL GENERATED ALWAYS AS (amount_before_tax * (1 + gst_pct / 100)) STORED,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES public.profiles(id)
);

-- 6. Receipts Table
CREATE TABLE IF NOT EXISTS public.receipts (
    receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no TEXT REFERENCES public.invoices(invoice_no) ON DELETE CASCADE,
    amount_received DECIMAL DEFAULT 0,
    tds_amount DECIMAL DEFAULT 0,
    receipt_date DATE NOT NULL,
    mode TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES public.profiles(id)
);

-- 7. Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- 9. Basic RLS Policies (All authenticated users can read, simplified for this portal)
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Simplify for now: Authenticated users can do everything
-- Note: In production, you would restrict these by user.role
CREATE POLICY "Allow all actions for authenticated users" ON public.clients FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all actions for authenticated users" ON public.proposals FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all actions for authenticated users" ON public.assignments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all actions for authenticated users" ON public.invoices FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all actions for authenticated users" ON public.receipts FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all actions for authenticated users" ON public.audit_logs FOR ALL USING (auth.role() = 'authenticated');

-- 10. Auto-create Profile Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email, 'MANAGER');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
