import pandas as pd
from io import BytesIO
from fastapi.responses import StreamingResponse
from datetime import datetime

def export_to_excel(data, entity_name, user_name):
    df = pd.DataFrame(data)
    
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Data')
        
        # Meta sheet
        meta_data = {
            "Field": ["Generated On", "Generated By", "Row Count"],
            "Value": [datetime.now().strftime("%Y-%m-%d %H:%M:%S"), user_name, len(df)]
        }
        meta_df = pd.DataFrame(meta_data)
        meta_df.to_excel(writer, index=False, sheet_name='Meta')

    output.seek(0)
    
    headers = {
        'Content-Disposition': f'attachment; filename="{entity_name}_{datetime.now().strftime("%Y%m%d")}.xlsx"'
    }
    return StreamingResponse(output, headers=headers, media_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

def export_to_csv(data, entity_name):
    df = pd.DataFrame(data)
    stream = BytesIO()
    df.to_csv(stream, index=False)
    stream.seek(0)
    
    headers = {
        'Content-Disposition': f'attachment; filename="{entity_name}_{datetime.now().strftime("%Y%m%d")}.csv"'
    }
    return StreamingResponse(stream, headers=headers, media_type='text/csv')
